hero_image: images/memory.png
theme: violet
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Cofio
description: Creu gêm gofio, lle mae'n rhaid i ti gofio ac ailadrodd dilyniant o liwiau ar hap!
original_url: https://codeclubprojects.org/en-GB/scratch/memory
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps: 
- title: Cyflwyniad
- title: Lliwiau ar hap
- title: 'Her: Ychwanegu sain'
- title: Ailadrodd y dilyniant
- title: Lefelau gwahanol
- title: Sgôr Uchel
- title: 'Her: Creu mwy o flociau'
- title: 'Her: Gwisg arall'
- title: 'Her: Lefelau y gêm'