---
hero_image: images/memory.png
theme: violet
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Igra pamćenja
description: Kreiraj igru pamćenja u kojoj treba da zapamtiš i ponoviš slučajan niz boja
original_url: https://codeclubprojects.org/en-GB/scratch/memory
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4.0.1
last_tested: 2017-01-01
steps:
  - title: Uvod
  - title: Šta će ti biti potrebno
  - title: Napravi niz boja
  - title: 'Izazov: dodavanje zvuka'
  - title: Ponavljanje niza
  - title: Više nivoa
  - title: Najbolji rezultat
  - title: 'Izazov: pravljenje više blokova'
  - title: 'Izazov: još jedan kostim'
  - title: 'Izazov: nivo težine'
