hero_image: images/memory.png
theme: violet
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Memoria
description: Crea un gioco di memoria, dove devi memorizzare e ripetere una sequenza di colori a caso!
original_url: https://codeclubprojects.org/en-GB/scratch/memory
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps: 
- title: Introduzione
- title: Colori a caso
- title: 'Sfida: Aggiungi un suono'
- title: Ripetere la sequenza
- title: Livelli multipli
- title: Punteggio alto
- title: 'Sfida: Crea altri blocchi'
- title: 'Sfida: Un altro costume'
- title: 'Sfida: Livello difficoltà'